### ISSUE TITLE
I'm getting this error, any guess

### ISSUE THREAD

**Issue by sibelius** [39otrebla/react-native-enhanced-listview#1]
Error: StaticRenderer.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.

Sticky header index 0 was outside the range {0, 0}

Cannot read property 'getHostNode' of null
TypeError: Cannot read property 'getHostNode' of null

react native 39

**Comment by 39otrebla** [comment]
This repository is not under active development. I will probably remove it in few days. I apologize for that, but  I realized the approach I used is not so much portable and, even, is some cases does not work (>100 rows on Android f.e.).

**Comment by sibelius** [comment]
FlatList landed on core, it just fix almost all errors

**Comment by 39otrebla** [comment]
Glad to hear it, I am going to close the issue.
